### ISSUE TITLE
曲库可以增加酷狗的吗?

### ISSUE THREAD

**Issue by ouyangxxx** [enzeberg/tonzhon-music#13]
如题,酷狗的曲库可以加吗?
谢谢

**Comment by ouyangxxx** [comment]
另外就是用手机进入网站听歌,切后台或者锁屏几分钟就停止播放了,有啥办法能保持锁屏后能一直播放吗?

**Comment by enzeberg** [comment]
酷狗上有什么歌是其他平台没有的吗？

**Comment by enzeberg** [comment]
> 另外就是用手机进入网站听歌,切后台或者锁屏几分钟就停止播放了,有啥办法能保持锁屏后能一直播放吗?

我没找到解决办法。我一般都是让手机一直开着。😂

**Comment by ouyangxxx** [comment]
> 酷狗上有什么歌是其他平台没有的吗？
一下子让我正经举例还真想不起来,说一个吧   "四万八千七-夜游之夜魔"最早是一个up发在b站的,根据九九八十一填词翻唱,后面B站下架,酷狗可以搜到,其他几个平台确实没搜到,网易云倒是有一个是"四万七八千（九九八十一）（翻自 乐正绫)-月灵纷飞"这是女声翻唱版
大概确实是酷狗上只是有少数冷门歌曲其他平台没有吧...
不过也是完全够用了,谢谢铜钟,谢谢enzeberg

**Comment by chenlongEX** [comment]
> > 另外就是用手机进入网站听歌,切后台或者锁屏几分钟就停止播放了,有啥办法能保持锁屏后能一直播放吗?
> 
> 我没找到解决办法。我一般都是让手机一直开着。😂

用miui的息屏听剧功能应该可以，不过我没试过。还有息屏挂机，这个是打游戏时用到的，不知道可不可以。
