### ISSUE TITLE
(酷我音乐)的歌曲加进自定义歌单以后没法删除

### ISSUE THREAD

**Issue by ouyangxxx** [enzeberg/tonzhon-music#16]
酷我音乐的歌大部分都没法删除,

**Comment by enzeberg** [comment]
感谢反馈！

目前 bug 已修复，新添加到歌单的酷我音乐的歌可以删除了。但由于历史包袱，之前添加的删除起来比较麻烦，所以目前还不能删除。

**Comment by mcj4444** [comment]
> 感谢反馈！
> 
> 目前bug已修复，新添加到歌单的酷我音乐的歌可以删除了。但由于历史包袱，之前添加的删除起来比较麻烦，所以目前还不能删除。

是凉了吗
