### ISSUE TITLE
凉了？

### ISSUE THREAD

**Issue by mcj4444** [enzeberg/tonzhon-music#21]
大了就被宰了吧

**Comment by scldt** [comment]
enzeberg 本人也不做回应，就比较奇怪。

**Comment by enzeberg** [comment]
铜钟换了个域名，回来了：[http://tonzhon.com](http://tonzhon.com) 。

**Comment by mcj4444** [comment]
谢谢



在 2021-03-20 10:30:11，"developer" ***@***.***> 写道：

铜钟换了个域名，回来了：http://tonzhon.com 。
