### ISSUE TITLE
没有专门存放云同步歌曲的服务器吗！每次换了域名总是要重新注册，以前同步的歌曲都没了。上次的域名是1.15.106.120，现在又换了tonzhon.com

### ISSUE THREAD

**Issue by chenlongEX** [enzeberg/tonzhon-music#25]
@enzeberg 没有专门存放云同步歌曲的服务器吗！每次换了域名总是要重新注册，以前同步的歌曲都没了。上次的域名是1.15.106.120，现在又换了tonzhon.com

**Comment by enzeberg** [comment]
@chenlongEX 这次域名不会再换了。
