### ISSUE TITLE
有没有放在服务器上的项目啊

### ISSUE THREAD

**Issue by DAIMAhuoquzhe** [enzeberg/tonzhon-music#26]
如题

**Comment by enzeberg** [comment]
https://github.com/enzeberg/tonzhon-lite-server

**Comment by DAIMAhuoquzhe** [comment]
宝塔上pm2直接运行app.js？

**Comment by enzeberg** [comment]
npm run prod

**Comment by Vari5** [comment]
> https://github.com/enzeberg/tonzhon-lite-server

现在是没有这个项目了吗

**Comment by enzeberg** [comment]
@Vari5 是的
