### ISSUE TITLE
你好，请问播放条那里的内容是怎么获取的，非常感谢

### ISSUE THREAD

**Issue by ShenGunNiTian** [enzeberg/tonzhon-music#3]

**Comment by ShenGunNiTian** [comment]
就是歌曲名、歌手名和时间

**Comment by enzeberg** [comment]
歌曲名和歌手名这些来自于播放列表数组中保存的歌曲对象，一个歌曲对象包括歌名，歌手和专辑等信息。这些归根结底还是因为调用了那三家平台的 API，我把那些 API 返回的结果进行了整理，构造了我们自己的歌曲对象。
至于歌曲时间，其中包括的总时长和播放进度都是加载了来自别的平台的音乐文件之后调用 <audio> DOM API 后获得的。

**Comment by xyyDDD** [comment]
你好,请问网易云的那些api应该都是加密过的，你是怎么解密的？

**Comment by ShenGunNiTian** [comment]
我这个也是用别人的，自己抓包很麻烦

**Comment by enzeberg** [comment]
@xyyDDD 网易的API我是从别的仓库截取的  ~>_<~
