### ISSUE TITLE
服务都启动起来了，就是接口报400，上次启动还正常访问

### ISSUE THREAD

**Issue by zhanghang318** [enzeberg/tonzhon-music#5]
![image](https://user-images.githubusercontent.com/31274300/51460494-9b574b00-1d96-11e9-925d-de8a29c00f33.png)

**Comment by hang4115819** [comment]
![image](https://user-images.githubusercontent.com/31274300/51506841-47e20d00-1e29-11e9-9a92-b4edde6fa982.png)
node没啥反应

**Comment by enzeberg** [comment]
好像是请求没有发到服务端，你试一下直接访问 http://localhost:8081/api/search?provider=netease&keyword=%E6%88%90%E9%BE%99&type=song 。如果这个能正常返回结果的话，就应该是客户端的问题。

**Comment by hang4115819** [comment]
直接访问是可以获取到数据的  
![image](https://user-images.githubusercontent.com/31274300/51515480-d9b04100-1e4e-11e9-9289-ae4b10002183.png)
可是客户端代码也找不出哪里报错呀，只是这里报错
![image](https://user-images.githubusercontent.com/31274300/51515578-30b61600-1e4f-11e9-9e67-311cd790f188.png)

**Comment by enzeberg** [comment]
确实诡异，不知道这个400是咋回事。我把我的 webpack dev server 中的代理去掉，访问 localhost:3000/api 只是收不到8081端口的响应，但不会返回400。要不你重新安装一下试试？

**Comment by hang4115819** [comment]
好的，我再安装一下试试
