### ISSUE TITLE
BUG,尝试听某歌之后,网站直接打不开了

### ISSUE THREAD

**Issue by ouyangxxx** [enzeberg/tonzhon-music#68]
是不是有什么反和谐机制?
我电脑是搜索了一个"雨中的故事",这个歌有几个版本,前面听了2个没事,然后有点了一个貌似是 什么 "雨中的故事G调" 啥的版本,然后网站直接白屏了,
不信邪我换了一个浏览器,正常开,然后又去搜索了同样的歌,还是那个 G调 然后同样情况发生了,网站有标题,内容白屏
以上是前几天的事了,后面经过清缓存,清cookie,到目前为止2个浏览依然不能正常打开网站.
就在刚刚我又拿手机试了下,听别的歌都正常,然后尝试搜索"雨中的故事",直接白屏,同时试了一个"烟雨蒙蒙",同样是白屏...其他多的就没做尝试了...............
如上,请问我是触发了啥和谐机制吗?我电脑上浏览器现在都不能打开网站了,也不知道怎么恢复....

**Comment by ouyangxxx** [comment]
有些歌尝试听的时候显示skipped,听不了,
作者大大,有空给看看吧.
谢谢

**Comment by enzeberg** [comment]
@ouyangxxx 
![雨中的故事](https://user-images.githubusercontent.com/18072932/234153084-eebbf000-996c-41c1-9c20-93682f1f9ec7.JPG)
![烟雨蒙蒙](https://user-images.githubusercontent.com/18072932/234153125-d13a649f-a3ce-4706-a7ae-3757509aaf91.JPG)
我这边听《雨中的故事》和《烟雨蒙蒙》都是正常的。

你把你浏览器的 Local Storage 的 currentSong 给我看一下，就像下面这样：
![currentSong](https://user-images.githubusercontent.com/18072932/234153200-bfcaec86-9ba6-431f-bafc-756e75e2cea1.JPG)

**Comment by enzeberg** [comment]
是，删除 currentSong 可以。因为那首歌的 `artists` 为 `[]`，在渲染的时候出了错，导致页面白屏。
现在已经修好了，你可以刷新铜钟看看是否还有白屏。

**Comment by ouyangxxx** [comment]
好的好的,OK了
谢谢大大

>
