### ISSUE TITLE
铜钟音乐的大佬你好

### ISSUE THREAD

**Issue by jinrumy611112** [enzeberg/tonzhon-music#69]
请教大佬，搜索结果出来在不同颜色的框里，这些不同颜色框代表的意思？

**Comment by enzeberg** [comment]
这些不同的颜色是为了便于用户在滚动页面的时候知道自己看到哪了，不至于混淆。

**Comment by ouyangxxx** [comment]
哈哈,用过早期版本的,我还盲猜是来自不同的曲库呢

**Comment by enzeberg** [comment]
因为铜钟有多个服务器，所以搜索结果比较多。用 不同的颜色 来 区分不同的搜索结果 可以 帮助用户知道自己看到哪了。
