### ISSUE TITLE
为什么在手机上无法进行登录操作

### ISSUE THREAD

**Issue by alexanderscholze** [enzeberg/tonzhon-music#76]

**Comment by alexanderscholze** [comment]
解决了，但是用户名和密码都是对的却一直提示错误

**Comment by enzeberg** [comment]
你登录成功了吗

**Comment by Johntse99** [comment]
就是使用edge浏览器的手机页面会掉登陆，但是电脑页面版就不会，不知道是什么问题呢

**Comment by enzeberg** [comment]
我改了一下，你现在试试呢？

**Comment by genshin666** [comment]
还是不行，可能是我记错密码了吧，但是按理说我又注册了用同样的密码第二个邮箱，应该不会记错的

**Comment by Johntse99** [comment]
可以了喔，非常感谢！

genshin666 ***@***.***> 于 2023年6月19日周一 17:15写道：
