### ISSUE TITLE
登录注册

### ISSUE THREAD

**Issue by xlzy520** [enzeberg/tonzhon-music#8]
你好，我看到http://tongzhong.xyz/my/favorites
这个网站是有登录注册的，我在这个项目里面没找到相关代码，这个功能方便看看吗，我想集成进来

**Comment by enzeberg** [comment]
@xlzy520 实在抱歉啊，注册登录这一块不方便开源。你如果是有这方面的问题的话，可以问我，虽然我懂得也不多 😂😂

**Comment by xlzy520** [comment]
@enzeberg 是因为有隐私信息吗？如果去掉这部分可以吗？只保留功能，因为我想要移植你这套系统，大佬

**Comment by enzeberg** [comment]
@xlzy520 哈哈，很感谢你的认可！不过这一块的代码我真地不方便公开，实在不好意思啊。
