### ISSUE TITLE
歌曲来源

### ISSUE THREAD

**Issue by hueralin** [enzeberg/tonzhon-music#84]
如题，请问歌曲来源是什么

**Comment by OpaoGuoNai** [comment]
我劝你不要不知好歹v( ͡• ͜ʖ ͡• )

**Comment by shlroland** [comment]
> 如题，请问歌曲来源是什么

随便搜索一下歌曲就能看出来，同时走了 qq 网易 咪咕 酷我的接口，所以有四个block的内容
