### ISSUE TITLE
关于广告：项目描述和实际不符

### ISSUE THREAD

**Issue by xiaoguyu** [enzeberg/tonzhon-music#85]
网站有广告，但是项目描述写着没有广告。。。
![Snipaste_2023-08-25_14-09-26](https://github.com/enzeberg/tonzhon-music/assets/22335025/19e1fb13-73a1-4bc9-b76f-342ac0fa6a4e)

**Comment by fuqiuxv** [comment]
并且不能被ABP等广告拦截插件默认识别，啊哈哈

**Comment by enzeberg** [comment]
这不是广告，而是友情链接，是为了支持一下 OpenMMLab 的活动和国内的深度学习行业，等 OpenMMLab 的活动结束了我就把这个链接删掉。 
这个链接是 7 月份刚刚加上的，"没有广告" 的文案是在这之前写的。
