### ISSUE TITLE
没有广告

### ISSUE THREAD

**Issue by lucasjinreal** [enzeberg/tonzhon-music#86]
![image](https://github.com/enzeberg/tonzhon-music/assets/21303438/75bee6c8-78f8-4c33-a4f2-e5293889e26c)

**Comment by enzeberg** [comment]
这不是广告，而是友情链接，是为了支持一下 OpenMMLab 的活动和国内的深度学习行业，等 OpenMMLab 的活动结束了我就把这个链接删掉。
这个链接是 7 月份刚刚加上的，"没有广告" 的文案是在这之前写的。
