### ISSUE TITLE
请求新功能：曲库增加酷我音乐

### ISSUE THREAD

**Issue by 3-2** [enzeberg/tonzhon-music#9]
例如刘欢的「我欲成仙」这首歌不在三家网站中的任何一家，而只在酷我音乐中。

**Comment by enzeberg** [comment]
感谢反馈！我已经把它加上了。
我欲成仙：[http://mini.tongzhong.xyz/search?keyword=%E6%88%91%E6%AC%B2%E6%88%90%E4%BB%99](http://mini.tongzhong.xyz/search?keyword=%E6%88%91%E6%AC%B2%E6%88%90%E4%BB%99)

**Comment by 3-2** [comment]
> 感谢反馈！我已经把它加上了。
> 我欲成仙：http://mini.tongzhong.xyz/search?keyword=%E6%88%91%E6%AC%B2%E6%88%90%E4%BB%99

谢谢！
请问 mini.tongzhong.xyz 跟 tongzhong.xyz 有什么区别呀，我才开始用这个网站，不是很清楚。而且我发现只有在 mini.tongzhong.xyz 能搜出酷我音乐，不带「mini」的 tongzhong.xyz 就搜不出来。

**Comment by enzeberg** [comment]
就是 mini.tongzhong.xyz 是 tongzhong.xyz 的极简版本，没有注册/登录等功能，但打开速度很快，并且是开源的，而 tongzhong.xyz 里面的一些功能不是开源的。
酷我那一块我还没往 tongzhong.xyz 上放，最近很忙，过段时间我可能会把它放上去。

**Comment by enzeberg** [comment]
@3-2 
「我欲成仙」: https://tonzhon.com/search?keyword=%E6%88%91%E6%AC%B2%E6%88%90%E4%BB%99
